{% set name = "pydatamail_google" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydatamail_google-{{ version }}.tar.gz
  sha256: 34bc8572f81f12c770a83fce2f867465f72104d414750e026df1272a11539837

build:
  entry_points:
    - pydatamail_google=pydatamail_google.__main__:command_line_parser
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - google-api-python-client >=2.51.0
    - google-auth >=2.8.0
    - google-auth-oauthlib >=0.5.2
    - matplotlib-base >=3.5.2
    - numpy >=1.23.0
    - pandas >=1.4.3
    - pydatamail >=0.0.6
    - python >=3.6
    - sqlalchemy >=1.4.39
    - tqdm >=4.64.0

test:
  imports:
    - pydatamail_google
  commands:
    - pip check
    - pydatamail_google --help
  requires:
    - pip

about:
  home: https://github.com/pyscioffice/pydatamail_google
  summary: Python interface to filter emails on Google Mail.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
